"""Deliverable stages: result workbooks (organisers' templates) and booktabs tables (+ CSV twins)."""

from __future__ import annotations

import csv
import json
from pathlib import Path
from typing import Any

import numpy as np
import pandas as pd

from forge import xlsx
from forge.context import StageContext
from forge.runner import stage
from pipelines.a.common import COLS, R_OUT_CM, R_TABLE_CM

HOUR = 3600.0


def _rows(frame: pd.DataFrame, t_min: float, columns: list[str]) -> list[list[Any]]:
    sel = frame[frame["t"] >= t_min]
    times = sel["t"].to_numpy(float)
    values = sel[columns].to_numpy(float)
    out: list[list[Any]] = []
    for t, row in zip(times, values):
        out.append([int(t + 0.5), *[None if np.isnan(v) else float(v) for v in row]])
    return out


@stage("results", deps=("q1", "q2", "q3", "q4"), description="Fill result1-4.xlsx from the organisers' templates")
def results(ctx: StageContext) -> dict[str, Any]:
    header = ["", *[float(r) for r in R_OUT_CM]]
    report: dict[str, Any] = {}
    for prob, name in (("q1", "result1.xlsx"), ("q2", "result2.xlsx")):
        d = ctx.dep(prob)
        temp = pd.read_parquet(d / "profiles_temp.parquet")
        moist = pd.read_parquet(d / "profiles_moist.parquet")
        sheets = {"温度": (header, _rows(temp, 1.0, COLS)), "水分浓度": (header, _rows(moist, 1.0, COLS))}
        report[name] = xlsx.write_result(ctx.templates / name, ctx.out(name), sheets)
        ctx.log.info("results.written", file=name, **report[name]["sheets"])
    moist3 = pd.read_parquet(ctx.dep("q3") / "profiles_moist.parquet")
    report["result3.xlsx"] = xlsx.write_result(
        ctx.templates / "result3.xlsx", ctx.out("result3.xlsx"), {"Sheet1": (header, _rows(moist3, 60.0, COLS))}
    )
    moist4 = pd.read_parquet(ctx.dep("q4") / "profiles_moist.parquet")
    header4 = [*header, "药材表面"]
    report["result4.xlsx"] = xlsx.write_result(
        ctx.templates / "result4.xlsx",
        ctx.out("result4.xlsx"),
        {"Sheet1": (header4, _rows(moist4, 60.0, [*COLS, "surface"]))},
    )
    ctx.write_json("results_report.json", report)
    return {name: info["sheets"] for name, info in report.items()}


# ----------------------------------------------------------------------------------------------
# tables
# ----------------------------------------------------------------------------------------------


def _fmt(v: Any, digits: int = 4) -> str:
    if v is None or (isinstance(v, float) and np.isnan(v)):
        return "--"
    if isinstance(v, str):
        return v
    return f"{float(v):.{digits}f}"


def _write_table(
    ctx: StageContext,
    name: str,
    caption: str,
    label: str,
    header: list[str],
    rows: list[list[Any]],
    *,
    digits: int | list[int] = 4,
    align: str | None = None,
    note: str | None = None,
) -> None:
    ncol = len(header)
    digs = [digits] * ncol if isinstance(digits, int) else digits
    align = align or ("l" + "r" * (ncol - 1))
    lines = [
        "% generated by forge (tables stage) — do not edit",
        "\\begin{table}[htbp]",
        "\\centering",
        f"\\caption{{{caption}}}",
        f"\\label{{{label}}}",
        f"\\begin{{tabular}}{{@{{}}{align}@{{}}}}",
        "\\toprule",
        " & ".join(header) + " \\\\",
        "\\midrule",
    ]
    for row in rows:
        lines.append(" & ".join(_fmt(v, digs[j]) for j, v in enumerate(row)) + " \\\\")
    lines += ["\\bottomrule", "\\end{tabular}"]
    if note:
        lines.append(f"\\par\\smallskip\\footnotesize {note}")
    lines.append("\\end{table}")
    ctx.out("tables", f"{name}.tex").write_text("\n".join(lines) + "\n", encoding="utf-8")
    with ctx.out("tables", f"{name}.csv").open("w", encoding="utf-8", newline="") as fh:
        writer = csv.writer(fh)
        writer.writerow(header)
        for row in rows:
            writer.writerow([_fmt(v, digs[j]) for j, v in enumerate(row)])


def _load(path: Path) -> Any:
    return json.loads(path.read_text(encoding="utf-8"))


@stage(
    "tables",
    deps=("q1", "q2", "q3", "q4", "convergence", "verification", "sensitivity", "extension"),
    description="LaTeX (booktabs) tables of the paper with CSV twins",
)
def tables(ctx: StageContext) -> dict[str, Any]:
    r_head = [f"{r:g}" for r in R_TABLE_CM]
    q1 = _load(ctx.dep("q1") / "tables.json")
    _write_table(
        ctx,
        "tab_q1_temp",
        "30 分钟内药材的温度（\\si{\\celsius}；列为到药材中心的距离/cm）",
        "tab:q1-temp",
        ["时间/s", *r_head],
        [[int(r[0]), *r[1:]] for r in q1["temp"]],
        digits=[0, 4, 4, 4, 4, 4],
    )
    _write_table(
        ctx,
        "tab_q1_moist",
        "30 分钟内药材的水分浓度（kg/kg；列为到药材中心的距离/cm）",
        "tab:q1-moist",
        ["时间/s", *r_head],
        [[int(r[0]), *r[1:]] for r in q1["moist"]],
        digits=[0, 4, 4, 4, 4, 4],
    )
    q2 = _load(ctx.dep("q2") / "tables.json")
    _write_table(
        ctx,
        "tab_q2_temp",
        "3 小时内药材的温度（\\si{\\celsius}；列为到药材中心的距离/cm）",
        "tab:q2-temp",
        ["时间/h", *r_head],
        [[r[0] / HOUR, *r[1:]] for r in q2["temp"]],
        digits=[1, 4, 4, 4, 4, 4],
    )
    _write_table(
        ctx,
        "tab_q2_moist",
        "3 小时内药材的水分浓度（kg/kg；列为到药材中心的距离/cm）",
        "tab:q2-moist",
        ["时间/h", *r_head],
        [[r[0] / HOUR, *r[1:]] for r in q2["moist"]],
        digits=[1, 4, 4, 4, 4, 4],
    )
    q3 = _load(ctx.dep("q3") / "tables.json")["moist"]
    rows3 = [[f"{r[0]:g}", *r[1:]] for r in q3[:-1]] + [[f"烘干结束时间（{q3[-1][0]:.2f} h）", *q3[-1][1:]]]
    _write_table(
        ctx,
        "tab_q3_moist",
        "药材烘干过程的水分浓度（kg/kg；固定半径 2 cm，附录 3 物性；列为到药材中心的距离/cm）",
        "tab:q3-moist",
        ["时间/h", *r_head],
        rows3,
        note="烘干结束时间为 $\\max_r C(r,t)<0.15$ 首次成立的精确时刻（事件求根），结果文件按 60 s 分辨率给出。",
    )
    q4 = _load(ctx.dep("q4") / "tables.json")["moist"]
    rows4 = [[f"{r[0]:g}", *r[1:]] for r in q4[:-1]] + [[f"烘干结束时间（{q4[-1][0]:.2f} h）", *q4[-1][1:]]]
    _write_table(
        ctx,
        "tab_q4_moist",
        "考虑尺寸变化的药材烘干过程水分浓度（kg/kg；附录 4 物性；列为到药材中心的距离/cm，超出当前半径处为“--”）",
        "tab:q4-moist",
        ["时间/h", *r_head, "药材表面"],
        rows4,
        note="固定物理位置的值由 $\\xi=r/R(t)$ 网格上的三次样条取得；“药材表面”为 $\\xi=1$ 的节点值。",
    )
    q4_alt = _load(ctx.dep("q4") / "tables_alt.json")
    rows4a = [[f"{r[0]:g}", *r[1:]] for r in q4_alt["moist"][:-1]] + [
        [f"烘干结束时间（{q4_alt['moist'][-1][0]:.2f} h）", *q4_alt["moist"][-1][1:]]
    ]
    _write_table(
        ctx,
        "tab_q4_moist_alt",
        f"备选写法（{q4_alt['formulation']}，MDR-0006）下的问题 4 水分浓度（kg/kg）",
        "tab:q4-moist-alt",
        ["时间/h", *r_head, "药材表面"],
        rows4a,
    )

    # convergence
    conv = _load(ctx.dep("convergence") / "convergence.json")
    rows_c: list[list[Any]] = []
    keys = [
        ("q1_temp", "问题 1 温度"),
        ("q1_moist", "问题 1 水分"),
        ("q2_temp", "问题 2 温度"),
        ("q2_moist", "问题 2 水分"),
        ("q3_moist", "问题 3 水分"),
        ("q4_moist", "问题 4 水分"),
    ]
    for key, label in keys:
        for row in conv["grid"][key]:
            rows_c.append([label, row["k"], row["dr_cm"], row["max_abs_error"], row.get("observed_order")])
    _write_table(
        ctx,
        "tab_convergence",
        f"网格收敛：以 $\\Delta r = 0.1/2^{{{conv['levels'] - 1}}}$ cm 为参照的最大绝对误差与观测阶数",
        "tab:convergence",
        ["量", "$k$", "$\\Delta r$/cm", "最大误差", "观测阶"],
        [[a, b, c, f"{d:.2e}", "--" if e is None else f"{e:.2f}"] for a, b, c, d, e in rows_c],
        digits=[0, 0, 4, 0, 0],
        align="llrrr",
    )
    rows_d = []
    for prob, label in (("q3", "问题 3"), ("q4", "问题 4")):
        for row in conv["grid"][f"{prob}_t_dry"]:
            rows_d.append([label, row["k"], row["dr_cm"], row["t_dry_h"], row.get("diff_to_finest_min")])
    _write_table(
        ctx,
        "tab_convergence_drytime",
        "烘干时间随网格加密的收敛（与最细网格之差，单位 min）",
        "tab:convergence-drytime",
        ["问题", "$k$", "$\\Delta r$/cm", "$t_{\\mathrm{end}}$/h", "与最细网格之差/min"],
        [[a, b, c, f"{d:.4f}", "--" if e is None else f"{e:.3f}"] for a, b, c, d, e in rows_d],
        digits=[0, 0, 4, 0, 0],
        align="llrrr",
    )
    rows_t = []
    for row in conv["time"].values():
        opt = row["options"]
        label = f"{opt['method']}, rtol={opt['rtol']:.0e}, atol={opt['atol']:.0e}"
        if opt.get("max_step"):
            label += f", $\\Delta t\\le{opt['max_step']:g}$ s"
        rows_t.append([label, f"{row['max_abs_diff_moist']:.2e}", f"{row['t_dry_diff_s']:.2f}", row["nfev"]])
    _write_table(
        ctx,
        "tab_time_independence",
        "时间积分无关性（问题 3，生产网格；与生产设置 "
        f"{ctx.cfg('a.time.method', 'BDF')}, rtol={float(ctx.cfg('a.time.rtol', 1e-9)):.0e}, "
        f"atol={float(ctx.cfg('a.time.atol', 1e-11)):.0e}、步长不限的差异）",
        "tab:time-independence",
        ["积分器、容差与最大步长", "水分最大差", "$t_{\\mathrm{end}}$ 差/s", "右端项调用次数"],
        rows_t,
        digits=[0, 0, 0, 0],
        align="lrrr",
        note="$\\Delta t\\le$ 行为限制最大步长的自适应 BDF（其余设置同生产）；"
        "步长限制改变的只是步序列，结果差异应在容差量级。",
    )

    # verification summary
    ver = _load(ctx.dep("verification") / "verification_report.json")
    checks: list[list[Any]] = []
    for prob in ("q1", "q2", "q3", "q4"):
        v = _load(ctx.dep(prob) / f"verification_{prob}.json")
        mb = v["moisture_balance"]
        ex = v["extremum"]
        checks.append(
            [
                f"问题 {prob[1]}",
                f"{mb['max_relative_residual']:.2e}",
                "是" if ex["moist_within_bounds"] and ex["temp_within_bounds"] else "否",
                "是" if ex["moist_monotone_in_r"] else "否",
                "是" if v["passed"] else "否",
            ]
        )
    _write_table(
        ctx,
        "tab_verification",
        "各问题的独立校验：水分守恒相对残差、极值原理、沿径向单调性、综合结论",
        "tab:verification",
        ["问题", "守恒残差", "极值原理", "单调性", "通过"],
        checks,
        digits=[0, 0, 0, 0, 0],
        align="lrccc",
    )
    rows_a = []
    for field, label in (("temp", "温度（Bi=%.3f）"), ("moist", "水分（Bi$_m$=%.3f）")):
        a = ver["analytic"][field]
        for row in a["levels"]:
            rows_a.append(
                [
                    label % a["biot"],
                    row["k"],
                    row["dr_cm"],
                    f"{row['max_abs_error']:.2e}",
                    "--" if row.get("observed_order") is None else f"{row['observed_order']:.2f}",
                ]
            )
    _write_table(
        ctx,
        "tab_analytic",
        "与常物性 Robin 圆柱贝塞尔级数解的最大绝对误差及观测阶数",
        "tab:analytic",
        ["量", "$k$", "$\\Delta r$/cm", "最大误差", "观测阶"],
        rows_a,
        digits=[0, 0, 4, 0, 0],
        align="llrrr",
    )

    # sensitivity
    sens = _load(ctx.dep("sensitivity") / "sensitivity.json")
    names = {
        "h": "$h$",
        "hm": "$h_m$",
        "D0": "$D_0$（问题 3）",
        "Cair": "$C_{\\mathrm{air}}$",
        "Tplateau": "$T_{\\mathrm{air}}$ 平台",
        "shrink": "收缩幅度 $s$（问题 4）",
        "D0q4": "$D_0$（问题 4）",
    }
    rows_s = []
    for row in sens["table"]:
        rows_s.append(
            [names.get(row["parameter"], row["parameter"]), row["base_h"]]
            + [row.get(f"x{f}") for f in sens["factors"]]
            + [row.get("elasticity")]
        )
    _write_table(
        ctx,
        "tab_sensitivity",
        "参数 ±10\\%、±20\\% 时的烘干时间（h）与弹性 $E=(\\Delta t_{\\mathrm{end}}/t_{\\mathrm{end}})/(\\Delta p/p)$",
        "tab:sensitivity",
        ["参数", "基准"] + [f"$\\times{f:g}$" for f in sens["factors"]] + ["弹性"],
        rows_s,
        digits=[0, 2, 2, 2, 2, 2, 3],
    )
    alt_names = {
        "plateau_last_sample": "平台取末样本（MDR-0003 方案 2）",
        "plateau_nominal": "平台取 50 \\si{\\celsius}、0.05（方案 3）",
        "face_arithmetic": "界面系数算术平均",
        "face_harmonic": "界面系数调和平均",
        "q4_eulerian": "问题 4 欧拉写法（含对流项）",
        "q4_lagrangian": "问题 4 拉格朗日写法",
        "q4_fixed_radius": "问题 4 物性、半径固定 2 cm",
        "q3_mean_criterion": "以平均含水率 $<0.15$ 为判据",
    }
    rows_alt = [[alt_names.get(r["case"], r["case"]), r["t_dry_h"], r["diff_pct"]] for r in sens["alternatives"]]
    _write_table(
        ctx,
        "tab_alternatives",
        "备选解释与离散化选择下的烘干时间（相对主结果的变化）",
        "tab:alternatives",
        ["备选", "$t_{\\mathrm{end}}$/h", "变化/\\%"],
        rows_alt,
        digits=[0, 2, 2],
        align="lrr",
    )
    # model-evaluation extension (MDR-0008)
    ext = _load(ctx.dep("extension") / "extension.json")
    rows_e: list[list[Any]] = [["题给模型（主结果）", "--", ext["base_t_dry_h"], 0.0]]
    for row in ext["variants"]:
        if row["case"] == "cap":
            name = f"蒸发通量受能量限制（湿球极限 $\\times{row['value']:g}$）"
            param = f"$j_{{\\max}}={row['cap_plateau_kg_m2_h']:.3f}$ kg/(m$^2\\cdot$h)"
        else:
            name = "驱动力取 $C_s-C_{\\mathrm{eq}}$（平衡含水率）"
            param = f"$C_{{\\mathrm{{eq}}}}={row['value']:g}$ kg/kg"
        rows_e.append([name, param, row["t_dry_h"], row["diff_pct"]])
    rows_e.append(
        [
            "纯能量下界（全程按湿球极限蒸发）",
            f"$j_{{\\max}}={ext['psychrometrics']['plateau']['flux_cap'] * HOUR:.3f}$ kg/(m$^2\\cdot$h)",
            ext["energy_bound_h"],
            100.0 * (ext["energy_bound_h"] / ext["base_t_dry_h"] - 1.0),
        ]
    )
    _write_table(
        ctx,
        "tab_extension",
        "模型评价扩展（MDR-0008，问题 3 设定）：能量限制与平衡含水率驱动力下的烘干时间及相对主结果的变化",
        "tab:extension",
        ["情形", "参数", "$t_{\\mathrm{end}}$/h", "变化/\\%"],
        rows_e,
        digits=[0, 0, 2, 1],
        align="llrr",
        note="湿球极限 $j_{\\max}=h\\,(T_{\\mathrm{air}}-T_{\\mathrm{wb}})/L_v$ 随烘房状态变化，表中给出恒温阶段的值。",
    )
    written = sorted(p.name for p in (ctx.stage_dir / "tables").glob("*.tex"))
    return {"tables": len(written), "files": written}
