"""Deliverable stages: result workbooks (organisers' templates) and booktabs tables (+ CSV twins)."""

from __future__ import annotations

import csv
import json
from pathlib import Path
from typing import Any

import numpy as np
import pandas as pd

from forge import xlsx
from forge.context import StageContext
from forge.runner import stage
from pipelines.a.common import COLS, R_OUT_CM, R_TABLE_CM
from pipelines.a.contracts import WHOLE_PROCESS_FILE

HOUR = 3600.0


def _rows(frame: pd.DataFrame, t_min: float, columns: list[str]) -> list[list[Any]]:
    sel = frame[frame["t"] >= t_min]
    times = sel["t"].to_numpy(float)
    values = sel[columns].to_numpy(float)
    out: list[list[Any]] = []
    for t, row in zip(times, values):
        out.append([int(t + 0.5), *[None if np.isnan(v) else float(v) for v in row]])
    return out


@stage("results", deps=("q1", "q2", "q3", "q4"), description="Fill result1-4.xlsx from the organisers' templates")
def results(ctx: StageContext) -> dict[str, Any]:
    header = ["", *[float(r) for r in R_OUT_CM]]
    report: dict[str, Any] = {}
    for prob, name in (("q1", "result1.xlsx"), ("q2", "result2.xlsx")):
        d = ctx.dep(prob)
        temp = pd.read_parquet(d / "profiles_temp.parquet")
        moist = pd.read_parquet(d / "profiles_moist.parquet")
        sheets = {"温度": (header, _rows(temp, 1.0, COLS)), "水分浓度": (header, _rows(moist, 1.0, COLS))}
        report[name] = xlsx.write_result(ctx.templates / name, ctx.out(name), sheets)
        ctx.log.info("results.written", file=name, **report[name]["sheets"])
    moist3 = pd.read_parquet(ctx.dep("q3") / "profiles_moist.parquet")
    report["result3.xlsx"] = xlsx.write_result(
        ctx.templates / "result3.xlsx", ctx.out("result3.xlsx"), {"Sheet1": (header, _rows(moist3, 60.0, COLS))}
    )
    moist4 = pd.read_parquet(ctx.dep("q4") / "profiles_moist.parquet")
    header4 = [*header, "药材表面"]
    report["result4.xlsx"] = xlsx.write_result(
        ctx.templates / "result4.xlsx",
        ctx.out("result4.xlsx"),
        {"Sheet1": (header4, _rows(moist4, 60.0, [*COLS, "surface"]))},
    )
    # supplementary deliverable (MDR-0005): the whole drying process, both fields, at the 60 s resolution the
    # problem itself uses for the whole process. result2.xlsx keeps the 1 s resolution over the 3 h of tables 3-4;
    # the same file at 1 s over the whole process would be 2.1e5 rows and ~57 MB (measured), beyond the
    # submission size budget, so the whole-process fields are delivered at 60 s instead.
    temp3 = pd.read_parquet(ctx.dep("q3") / "profiles_temp.parquet")
    sheets_full = {
        "温度": (header, _rows(temp3, 60.0, COLS)),
        "水分浓度": (header, _rows(moist3, 60.0, COLS)),
    }
    report[WHOLE_PROCESS_FILE] = xlsx.write_result(
        ctx.templates / "result2.xlsx", ctx.out(WHOLE_PROCESS_FILE), sheets_full
    )
    ctx.write_json("results_report.json", report)
    return {name: info["sheets"] for name, info in report.items()}


# ----------------------------------------------------------------------------------------------
# tables
# ----------------------------------------------------------------------------------------------


def _fmt(v: Any, digits: int = 4) -> str:
    if v is None or (isinstance(v, float) and np.isnan(v)):
        return "--"
    if isinstance(v, str):
        return v
    return f"{float(v):.{digits}f}"


def _write_table(
    ctx: StageContext,
    name: str,
    caption: str,
    label: str,
    header: list[str],
    rows: list[list[Any]],
    *,
    digits: int | list[int] = 4,
    align: str | None = None,
    note: str | None = None,
) -> None:
    ncol = len(header)
    digs = [digits] * ncol if isinstance(digits, int) else digits
    align = align or ("l" + "r" * (ncol - 1))
    lines = [
        "% generated by forge (tables stage) — do not edit",
        "\\begin{table}[htbp]",
        "\\centering",
        f"\\caption{{{caption}}}",
        f"\\label{{{label}}}",
        f"\\begin{{tabular}}{{@{{}}{align}@{{}}}}",
        "\\toprule",
        " & ".join(header) + " \\\\",
        "\\midrule",
    ]
    for row in rows:
        lines.append(" & ".join(_fmt(v, digs[j]) for j, v in enumerate(row)) + " \\\\")
    lines += ["\\bottomrule", "\\end{tabular}"]
    if note:
        lines.append(f"\\par\\smallskip\\footnotesize {note}")
    lines.append("\\end{table}")
    ctx.out("tables", f"{name}.tex").write_text("\n".join(lines) + "\n", encoding="utf-8")
    with ctx.out("tables", f"{name}.csv").open("w", encoding="utf-8", newline="") as fh:
        writer = csv.writer(fh)
        writer.writerow(header)
        for row in rows:
            writer.writerow([_fmt(v, digs[j]) for j, v in enumerate(row)])


def _load(path: Path) -> Any:
    return json.loads(path.read_text(encoding="utf-8"))


@stage(
    "tables",
    deps=("q1", "q2", "q3", "q4", "convergence", "verification", "sensitivity", "extension"),
    description="LaTeX (booktabs) tables of the paper with CSV twins",
)
def tables(ctx: StageContext) -> dict[str, Any]:
    r_head = [f"{r:g}" for r in R_TABLE_CM]
    q1 = _load(ctx.dep("q1") / "tables.json")
    _write_table(
        ctx,
        "tab_q1_temp",
        "30 分钟内药材的温度（\\si{\\celsius}；列为到药材中心的距离/cm）",
        "tab:q1-temp",
        ["时间/s", *r_head],
        [[int(r[0]), *r[1:]] for r in q1["temp"]],
        digits=[0, 4, 4, 4, 4, 4],
    )
    _write_table(
        ctx,
        "tab_q1_moist",
        "30 分钟内药材的水分浓度（kg/kg；列为到药材中心的距离/cm）",
        "tab:q1-moist",
        ["时间/s", *r_head],
        [[int(r[0]), *r[1:]] for r in q1["moist"]],
        digits=[0, 4, 4, 4, 4, 4],
    )
    q2 = _load(ctx.dep("q2") / "tables.json")
    _write_table(
        ctx,
        "tab_q2_temp",
        "3 小时内药材的温度（\\si{\\celsius}；列为到药材中心的距离/cm）",
        "tab:q2-temp",
        ["时间/h", *r_head],
        [[r[0] / HOUR, *r[1:]] for r in q2["temp"]],
        digits=[1, 4, 4, 4, 4, 4],
    )
    _write_table(
        ctx,
        "tab_q2_moist",
        "3 小时内药材的水分浓度（kg/kg；列为到药材中心的距离/cm）",
        "tab:q2-moist",
        ["时间/h", *r_head],
        [[r[0] / HOUR, *r[1:]] for r in q2["moist"]],
        digits=[1, 4, 4, 4, 4, 4],
    )
    q3 = _load(ctx.dep("q3") / "tables.json")["moist"]
    rows3 = [[f"{r[0]:g}", *r[1:]] for r in q3[:-1]] + [[f"烘干结束时间（{q3[-1][0]:.2f} h）", *q3[-1][1:]]]
    _write_table(
        ctx,
        "tab_q3_moist",
        "药材烘干过程的水分浓度（kg/kg；固定半径 2 cm，附录 3 物性；列为到药材中心的距离/cm）",
        "tab:q3-moist",
        ["时间/h", *r_head],
        rows3,
        note="烘干结束时间为 $\\max_r C(r,t)<0.15$ 首次成立的精确时刻（事件求根），结果文件按 60 s 分辨率给出。",
    )
    q4 = _load(ctx.dep("q4") / "tables.json")["moist"]
    rows4 = [[f"{r[0]:g}", *r[1:]] for r in q4[:-1]] + [[f"烘干结束时间（{q4[-1][0]:.2f} h）", *q4[-1][1:]]]
    _write_table(
        ctx,
        "tab_q4_moist",
        "考虑尺寸变化的药材烘干过程水分浓度（kg/kg；附录 4 物性；列为到药材中心的距离/cm，超出当前半径处为“--”）",
        "tab:q4-moist",
        ["时间/h", *r_head, "药材表面"],
        rows4,
        note="固定物理位置的值由 $\\xi=r/R(t)$ 网格上的三次样条取得；“药材表面”为 $\\xi=1$ 的节点值。",
    )
    q4_alt = _load(ctx.dep("q4") / "tables_alt.json")
    rows4a = [[f"{r[0]:g}", *r[1:]] for r in q4_alt["moist"][:-1]] + [
        [f"烘干结束时间（{q4_alt['moist'][-1][0]:.2f} h）", *q4_alt["moist"][-1][1:]]
    ]
    _write_table(
        ctx,
        "tab_q4_moist_alt",
        f"备选写法（{q4_alt['formulation']}，MDR-0006）下的问题 4 水分浓度（kg/kg）",
        "tab:q4-moist-alt",
        ["时间/h", *r_head, "药材表面"],
        rows4a,
    )

    # convergence
    conv = _load(ctx.dep("convergence") / "convergence.json")
    rows_c: list[list[Any]] = []
    keys = [
        ("q1_temp", "问题 1 温度"),
        ("q1_moist", "问题 1 水分"),
        ("q2_temp", "问题 2 温度"),
        ("q2_moist", "问题 2 水分"),
        ("q3_moist", "问题 3 水分"),
        ("q4_moist", "问题 4 水分"),
    ]
    for key, label in keys:
        for row in conv["grid"][key]:
            rows_c.append(
                [
                    label,
                    row["k"],
                    row["dr_cm"],
                    row["max_abs_error"],
                    row.get("observed_order"),
                    row.get("observed_order_triplet"),
                ]
            )
    _write_table(
        ctx,
        "tab_convergence",
        f"网格收敛：以 $\\Delta r = 0.1/2^{{{conv['levels'] - 1}}}$ cm 为参照的最大绝对误差与两种观测阶",
        "tab:convergence",
        ["量", "$k$", "$\\Delta r$/cm", "最大误差", "自收敛阶", "三网格阶"],
        [
            [a, b, c, f"{d:.2e}", "--" if e is None else f"{e:.2f}", "--" if f is None else f"{f:.2f}"]
            for a, b, c, d, e, f in rows_c
        ],
        digits=[0, 0, 4, 0, 0, 0],
        align="llrrrr",
        note="“自收敛阶”$p_k=\\log_2(e_k/e_{k+1})$ 以最细网格为参照，最后一对网格被系统性抬高 "
        "$\\log_2[(1-4^{-(m-k)})/(1-4^{-(m-k-1)})]$（二阶格式在 $m-k=2$ 时为 2.32）；“三网格阶”"
        "$p_k=\\log_2(\\lVert u_k-u_{k+1}\\rVert_\\infty/\\lVert u_{k+1}-u_{k+2}\\rVert_\\infty)$ "
        "不需要参照解，无此偏置（MDR-0011）。",
    )
    rows_d = []
    for prob, label in (("q3", "问题 3"), ("q4", "问题 4")):
        for row in conv["grid"][f"{prob}_t_dry"]:
            rows_d.append(
                [
                    label,
                    row["k"],
                    row["dr_cm"],
                    row["t_dry_h"],
                    row.get("diff_to_finest_min"),
                    row.get("observed_order_triplet"),
                ]
            )
    _write_table(
        ctx,
        "tab_convergence_drytime",
        "烘干时间随网格加密的收敛（与最细网格之差，单位 min）与三网格观测阶",
        "tab:convergence-drytime",
        ["问题", "$k$", "$\\Delta r$/cm", "$t_{\\mathrm{end}}$/h", "与最细网格之差/min", "三网格阶"],
        [
            [a, b, c, f"{d:.4f}", "--" if e is None else f"{e:.3f}", "--" if f is None else f"{f:.2f}"]
            for a, b, c, d, e, f in rows_d
        ],
        digits=[0, 0, 4, 0, 0, 0],
        align="llrrrr",
        note="$t_{\\mathrm{end}}$ 的收敛阶低于场量本身：判据时刻随网格移动，误差同时包含解误差与穿零时刻的移动。"
        "Richardson 外推按该观测阶进行（正文第~\\ref{subsec:gridconv} 小节）。",
    )
    rows_t = []
    for row in conv["time"].values():
        opt = row["options"]
        label = f"{opt['method']}, rtol={opt['rtol']:.0e}, atol={opt['atol']:.0e}"
        if opt.get("max_step"):
            label += f", $\\Delta t\\le{opt['max_step']:g}$ s"
        rows_t.append([label, f"{row['max_abs_diff_moist']:.2e}", f"{row['t_dry_diff_s']:.2f}", row["nfev"]])
    _write_table(
        ctx,
        "tab_time_independence",
        "时间积分无关性（问题 3，生产网格；与生产设置 "
        f"{ctx.cfg('a.time.method', 'BDF')}, rtol={float(ctx.cfg('a.time.rtol', 1e-9)):.0e}, "
        f"atol={float(ctx.cfg('a.time.atol', 1e-11)):.0e}、步长不限的差异）",
        "tab:time-independence",
        ["积分器、容差与最大步长", "水分最大差", "$t_{\\mathrm{end}}$ 差/s", "右端项调用次数"],
        rows_t,
        digits=[0, 0, 0, 0],
        align="lrrr",
        note="$\\Delta t\\le$ 行为限制最大步长的自适应 BDF（其余设置同生产）；"
        "步长限制改变的只是步序列，结果差异应在容差量级。",
    )

    # verification summary
    ver = _load(ctx.dep("verification") / "verification_report.json")
    checks: list[list[Any]] = []
    for prob in ("q1", "q2", "q3", "q4"):
        v = _load(ctx.dep(prob) / f"verification_{prob}.json")
        mb = v["moisture_balance"]
        ex = v["extremum"]
        sampled = mb.get("sampled", {}).get("max_relative_residual")
        checks.append(
            [
                f"问题 {prob[1]}",
                f"{mb['max_relative_residual']:.2e}",
                "--" if sampled is None else f"{sampled:.2e}",
                "是" if ex["moist_within_bounds"] and ex["temp_within_bounds"] else "否",
                "是" if ex["moist_monotone_in_r"] else "否",
                "是" if v["passed"] else "否",
            ]
        )
    _write_table(
        ctx,
        "tab_verification",
        "各问题的独立校验：水分守恒的两种相对残差、极值原理、沿径向单调性、综合结论",
        "tab:verification",
        ["问题", "不变量残差", "重采样残差", "极值原理", "单调性", "通过"],
        checks,
        digits=[0, 0, 0, 0, 0, 0],
        align="lrrccc",
        note="“不变量残差”比较离散存量与积分器内累积的边界通量（半离散系统的精确线性不变量，检验格式本身）；"
        "“重采样残差”由输出样本按梯形法独立重算通量积分，受输出间隔的梯形误差限制，检验的是实际通量。",
    )
    rows_a = []
    analytic_keys = [
        ("temp", "常环境温度（Bi=%.3f）"),
        ("moist", "常环境水分（Bi$_m$=%.3f）"),
        ("duhamel", "问题 1 温度、Duhamel（Bi=%.3f）"),
    ]
    for field, label in analytic_keys:
        a = ver["analytic"][field]
        for row in a["levels"]:
            rows_a.append(
                [
                    label % a["biot"],
                    row["k"],
                    row["dr_cm"],
                    f"{row['max_abs_error']:.2e}",
                    "--" if row.get("observed_order") is None else f"{row['observed_order']:.2f}",
                ]
            )
    _write_table(
        ctx,
        "tab_analytic",
        "与 Robin 圆柱级数解的最大绝对误差及观测阶数（前两组为人为构造的常环境算例，第三组为问题 1 本身）",
        "tab:analytic",
        ["量", "$k$", "$\\Delta r$/cm", "最大误差", "观测阶"],
        rows_a,
        digits=[0, 0, 4, 0, 0],
        align="llrrr",
        note="第三组把附件 1 的分段线性烘房温度用 Duhamel 叠加代入级数解，因而是问题 1 温度场的\\textbf{真解}对照，"
        "而非常环境算例。",
    )

    # output-grid (result-file resolution) refinement study
    og = conv.get("output_grid", {})
    og_names = {
        "q1_temp": "问题 1 温度",
        "q1_moist": "问题 1 水分",
        "q2_temp": "问题 2 温度",
        "q2_moist": "问题 2 水分",
    }
    rows_og = [
        [
            og_names.get(key, key),
            f"{row['cells_total']:d}",
            f"{row['production_error']:.2e}",
            f"{row['max_at_t_s']:g} s / {row['max_at_r_cm']:g} cm",
            f"{row['observed_order']:.2f}",
            f"{row['cells_above_half_ulp']:d}",
            f"{row['last_above_half_ulp_t_s']:g}",
            f"{row['error_after_half_ulp']:.1e}",
        ]
        for key, row in og.items()
    ]
    if rows_og:
        _write_table(
            ctx,
            "tab_outputgrid",
            "结果文件完整输出网格（每 1 s $\\times$ 每 0.1 cm）上的离散误差与四位小数的可靠性",
            "tab:outputgrid",
            [
                "量",
                "单元数",
                "最大误差",
                "误差最大处",
                "三网格阶",
                "误差 $>5\\times10^{-5}$ 的单元",
                "最后一处/s",
                "此后最大误差",
            ],
            rows_og,
            digits=[0, 0, 0, 0, 0, 0, 0, 0],
            align="lrrlrrrr",
            note="误差相对由 $k=6,7$ 两级网格作 Richardson 外推得到的极限。"
            "$5\\times10^{-5}$ 是四位小数的半个末位：误差低于它的单元，第四位小数由离散误差决定的可能性已被排除；"
            "“最后一处”之后的全部输出时刻上误差见末列。",
        )

    # sensitivity
    sens = _load(ctx.dep("sensitivity") / "sensitivity.json")
    names = {
        "h": "$h$",
        "hm": "$h_m$",
        "D0": "$D_0$（问题 3）",
        "Cair": "$C_{\\mathrm{air}}$",
        "Tplateau": "$T_{\\mathrm{air}}$ 平台",
        "shrink": "收缩幅度 $s$（问题 4）",
        "D0q4": "$D_0$（问题 4）",
    }
    rows_s = []
    for row in sens["table"]:
        rows_s.append(
            [names.get(row["parameter"], row["parameter"]), row["base_h"]]
            + [row.get(f"x{f}") for f in sens["factors"]]
            + [row.get("elasticity")]
        )
    _write_table(
        ctx,
        "tab_sensitivity",
        "参数 ±10\\%、±20\\% 时的烘干时间（h）与弹性 $E=(\\Delta t_{\\mathrm{end}}/t_{\\mathrm{end}})/(\\Delta p/p)$",
        "tab:sensitivity",
        ["参数", "基准"] + [f"$\\times{f:g}$" for f in sens["factors"]] + ["弹性"],
        rows_s,
        digits=[0, 2, 2, 2, 2, 2, 3],
    )
    alt_names = {
        "plateau_last_sample": "平台取末样本（MDR-0003 方案 2）",
        "plateau_nominal": "平台取 50 \\si{\\celsius}、0.05（方案 3）",
        "face_arithmetic": "界面系数算术平均",
        "face_harmonic": "界面系数调和平均",
        "q4_eulerian": "问题 4 欧拉写法（含对流项）",
        "q4_lagrangian": "问题 4 拉格朗日写法",
        "q4_fixed_radius": "问题 4 物性、半径固定 2 cm",
        "q3_mean_criterion": "以平均含水率 $<0.15$ 为判据",
        "mass_conservative": "守恒型水分方程 $\\partial_t(\\rho_sC)=\\nabla\\!\\cdot\\!(\\rho_sD\\nabla C)$",
    }
    rows_alt = [[alt_names.get(r["case"], r["case"]), r["t_dry_h"], r["diff_pct"]] for r in sens["alternatives"]]
    _write_table(
        ctx,
        "tab_alternatives",
        "备选解释与离散化选择下的烘干时间（相对主结果的变化）",
        "tab:alternatives",
        ["备选", "$t_{\\mathrm{end}}$/h", "变化/\\%"],
        rows_alt,
        digits=[0, 2, 2],
        align="lrr",
    )
    # model-evaluation extension (MDR-0008)
    ext = _load(ctx.dep("extension") / "extension.json")
    rows_e: list[list[Any]] = [["题给模型（主结果）", "--", ext["base_t_dry_h"], 0.0]]
    for row in ext["variants"]:
        if row["case"] == "caplocal":
            name = "蒸发通量受能量限制（换算用局部 $\\rho_s(C_s)$）"
            param = f"$j_{{\\max}}={row['cap_plateau_kg_m2_h']:.3f}$ kg/(m$^2\\cdot$h)"
        elif row["case"] == "cap":
            name = f"蒸发通量受能量限制（湿球极限 $\\times{row['value']:g}$）"
            param = f"$j_{{\\max}}={row['cap_plateau_kg_m2_h']:.3f}$ kg/(m$^2\\cdot$h)"
        else:
            name = "驱动力取 $C_s-C_{\\mathrm{eq}}$（平衡含水率）"
            param = f"$C_{{\\mathrm{{eq}}}}={row['value']:g}$ kg/kg"
        rows_e.append([name, param, row["t_dry_h"], row["diff_pct"]])
    rows_e.append(
        [
            "纯能量下界（全程按湿球极限蒸发）",
            f"$j_{{\\max}}={ext['psychrometrics']['plateau']['flux_cap'] * HOUR:.3f}$ kg/(m$^2\\cdot$h)",
            ext["energy_bound_h"],
            100.0 * (ext["energy_bound_h"] / ext["base_t_dry_h"] - 1.0),
        ]
    )
    _write_table(
        ctx,
        "tab_extension",
        "模型评价扩展（MDR-0008，问题 3 设定）：能量限制与平衡含水率驱动力下的烘干时间及相对主结果的变化",
        "tab:extension",
        ["情形", "参数", "$t_{\\mathrm{end}}$/h", "变化/\\%"],
        rows_e,
        digits=[0, 0, 2, 1],
        align="llrr",
        note="湿球极限 $j_{\\max}=h\\,(T_{\\mathrm{air}}-T_{\\mathrm{wb}})/L_v$ 随烘房状态变化，表中给出恒温阶段的值。",
    )
    written = sorted(p.name for p in (ctx.stage_dir / "tables").glob("*.tex"))
    return {"tables": len(written), "files": written}
